benford/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data.urls', namespace='data')),
]

data/urls.py
from django.urls import path
from data import views

app_name = 'data'

urlpatterns = [
    path('', views.ChartView.as_view(), name='chart'),
    path('import', views.ImportView.as_view(), name='import'),
    path('person/<slug:slug>/<int:pk>', views.PersonReportDetailView.as_view(), name='person_report')
]

data/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class ImportData(models.Model):
    person = models.CharField(max_length=255, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.person

    @property
    def slug(self):
        return slugify(self.person)

    def get_absolute_url(self):
        return reverse('data:person_report', kwargs={'slug': self.slug, 'pk': self.pk})


class DataItem(models.Model):
    import_data = models.ForeignKey(ImportData, related_name='dataitems_importdata', on_delete=models.SET_NULL,
                                    null=True, blank=True)
    state = models.CharField(max_length=255)
    town = models.CharField(max_length=255)
    value_1 = models.IntegerField(help_text='7_2009', blank=True, null=True)
    value_2 = models.IntegerField(help_text='value_2', blank=True, null=True)
    value_3 = models.IntegerField(help_text='value_3', blank=True, null=True)
    value_4 = models.FloatField(help_text='value_4', blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.state, self.town)

data/forms.py
from django import forms


class UploadFileForm(forms.Form):
    name_of_person = forms.CharField(max_length=100)
    file = forms.FileField()

data/views.py
import csv
import io
from collections import Counter
from math import log10

from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, DetailView
from data import forms
from data import models


class ChartView(TemplateView):
    template_name = 'data/chart.html'

    @staticmethod
    def first_number(value):
        for i in value:
            yield int(str(i)[0])

    @staticmethod
    def get_7_2009(data):
        c_dict = Counter(data)
        size = sum(c_dict.values())
        result = [c_dict[k] / size if size else 0 for k in range(1, 10)]
        return result

    def get_context_data(self, **kwargs):
        last_import_data = models.ImportData.objects.last()
        context = super().get_context_data(**kwargs)
        context['results'] = [round(i*100, 2) for i in self.get_7_2009(self.first_number(last_import_data.dataitems_importdata.values_list("value_1", flat=True)))] if last_import_data else None
        context['expected'] = [round(log10(1 + 1 / d)*100, 2) for d in range(1, 10)]
        context['labels'] = list(range(1, 10))
        context['person'] = last_import_data.person if last_import_data else None
        context['personal_reports'] = models.ImportData.objects.all().order_by('-date')
        return context


class ImportView(FormView):
    template_name = 'data/import.html'
    form_class = forms.UploadFileForm
    success_url = reverse_lazy('data:chart')

    @staticmethod
    def valid_headers(word):
        return [char.isalpha() or char.isalnum() or '_' in char for char in word]

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.form_class)
        file = request.FILES['file']
        if form.is_valid():
            data_set = file.read().decode('UTF-8')
            io_string = io.StringIO(data_set)

            d_reader = csv.DictReader(io_string, delimiter='\t')
            headers = d_reader.fieldnames
            if not all(self.valid_headers(headers)):
                messages.warning(request, 'Please check headers in uploading file. Can be numbers data there.')
                return self.form_invalid(form)

            importdata = models.ImportData.objects.create(person=form.cleaned_data['name_of_person'])
            for index, column in enumerate(csv.reader(io_string, delimiter='\t')):
                try:
                    models.DataItem.objects.create(import_data=importdata, state=column[0], town=column[1],
                                                    value_1=column[2], value_2=column[3], value_3=column[4],
                                                    value_4=column[5])
                except ValueError:
                    messages.warning(request, 'Data can be in incorrect table.')
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['personal_reports'] = models.ImportData.objects.all().order_by('-date')
        return context


class PersonReportDetailView(DetailView):
    model = models.ImportData
    template_name = 'data/person_report.html'

    @staticmethod
    def first_number(value):
        for i in value:
            yield int(str(i)[0])

    @staticmethod
    def get_7_2009(data):
        c_dict = Counter(data)
        size = sum(c_dict.values())
        result = [c_dict[k] / size if size else 0 for k in range(1, 10)]
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['personal_reports'] = models.ImportData.objects.all().order_by('-date')
        context['results'] = [round(i*100, 2) for i in self.get_7_2009(self.first_number(self.get_object().dataitems_importdata.values_list("value_1", flat=True)))]
        context['expected'] = [round(log10(1 + 1 / d)*100, 2) for d in range(1, 10)]
        context['labels'] = list(range(1, 10))
        return context

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Code Poets App</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Favicons -->
<meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="/">Code Poets App</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="/admin">Admin</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    {% block side_menu %}
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'data:chart' %}">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'data:import' %}">
              <span data-feather="file"></span>
              Make file import
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Reports from users</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          {% if personal_reports %}
            {% for person in personal_reports %}
            <li class="nav-item">
              <a class="nav-link" href="{{ person.get_absolute_url }}">
                <span data-feather="file-text"></span>
                {{ person }}
              </a>
            </li>
            {% endfor %}
          {% else %}
            <div class="alert alert-warning" role="alert">
              <p>No user has done the import.</p>
            </div>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% endblock side_menu %}

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    {% block content %}
    {% endblock content %}
    </main>
  </div>
</div>
{% block js %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="{% static 'js/dashboard.js' %}"></script></body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
 <script>

    var config = {
      type: 'bar',
      data: {
        datasets: [{
          borderColor: ['#005082'],
          backgroundColor: '#005082',
          data: {{ results|safe }},
          label: 'Data'
        },
        {
          borderColor: ['#ef6c57'],
          backgroundColor: '#ef6c57',
          data: {{ expected|safe }},
          label: 'Benford'
        }],
        labels: {{ labels|safe }},
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('bar_chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };
  </script>
{% endblock js %}
</html>

templates/data/chart.html
{% extends 'base.html' %}

{% block content %}
    {% if not results %}
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            <div class="alert alert-warning" role="alert">
                There is no data in database, please import some data.
            </div>
        </div>
    {% else %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Last report from {{ person }}</h1>
      </div>
      <canvas class="my-4 w-100" id="bar_chart" width="900" height="380"></canvas>
    {% endif %}
{% endblock content %}

templates/data/import.html
{% extends 'base.html' %}

{% block content %}
<h2>Import your report</h2>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning" role="alert">
          {{ message }}
        </div>
    {% endfor %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data" role="form">
                {% csrf_token %}
                {% include 'includes/bs4_form.html' with form=form %}
                <input type="submit" class="btn btn-primary mb-2" value="Upload!" />
            </form>
	    </div>
    </div>
</div>
{% endblock content %}

templates/data/person_report.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Personal report by {{ object.person }}</h1>
      </div>
      <canvas class="my-4 w-100" id="bar_chart" width="900" height="380"></canvas>
{% endblock content %}

templates/includes/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}